name: ♻️ Sync Upstream ♻️
#MAX_RUNTIME: 02 Minutes */10 * * * * 

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *" #@every 1hrs
#------------------------------------------------------------------------------------#
jobs:
    sync-upstream:
      name: Sync Upstream
      runs-on: ubuntu-latest
      permissions: 
        contents: write

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
          fetch-depth: 1
          filter: "blob:none"

      - name: Setup Env
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          ##Install coreutils
          sudo apt-get update -y -qq && sudo apt-get install curl coreutils dos2unix file findutils gawk git jq moreutils rsync tar xz-utils util-linux wget zip -y -qq
          ##Install Addons
          #https://github.com/pkgforge/devscripts/blob/main/Linux/install_bins_curl.sh
          #bash <(curl -qfsSL "https://raw.githubusercontent.com/pkgforge/devscripts/refs/heads/main/Linux/install_bins_curl.sh")
          ##Create Output Dir
          mkdir -p "${GITHUB_WORKSPACE}/main"
          echo "GIT_TERMINAL_PROMPT=0" >> "${GITHUB_ENV}"
          echo "GIT_ASKPASS=/bin/echo" >> "${GITHUB_ENV}"
          git config --global "user.email" "AjamX101@gmail.com"
          git config --global "user.name" "Azathothas"
        continue-on-error: true

      - name: Sync "${GITHUB_WORKSPACE}/main" <-- "(https://github.com/ivan-hc/AM)"
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          ##Main
          pushd "$(mktemp -d)" &>/dev/null && git clone --filter="blob:none" --quiet "https://github.com/ivan-hc/AM" && cd "./AM"
          LATEST_COMMIT="$(git rev-parse HEAD | tr -d "[:space:]")" && export LATEST_COMMIT="${LATEST_COMMIT}"
          LATEST_COMMI_M="$(git log -1 --pretty="%B" | sed -e '/^[[:space:]]*$/d;1q')" && export LATEST_COMMIT="${LATEST_COMMIT}"
          echo "LATEST_COMMI_M=${LATEST_COMMI_M}" >> "${GITHUB_ENV}"
          PREV_COMMIT="$(cat "${GITHUB_WORKSPACE}/main/.github/LATEST.txt" 2>/dev/null)" && export PREV_COMMIT="${PREV_COMMIT}"
          if [ "${LATEST_COMMIT}" != "${PREV_COMMIT}" ]; then
            #Sync Repo
             echo "${LATEST_COMMIT}" > "${GITHUB_WORKSPACE}/main/.github/LATEST.txt"
             sed '/^$/d' -i "${GITHUB_WORKSPACE}/main/.github/LATEST.txt"
             rm -rfv "./.git/" "./.githooks/" "./.github/" 2>/dev/null
             rsync -achLv --remove-source-files --exclude="./.git/**" --exclude="./.github/**" "./" "${GITHUB_WORKSPACE}/main/"
          fi
          popd &>/dev/null
        continue-on-error: true

      - name: Remove Reference
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          ##ivan-hc/AM --> pkgforge-community/AM-HF-SYNC
          find "${GITHUB_WORKSPACE}/main" -name ".git*" -prune -o -type f -exec sed 's#ivan-hc/AM#pkgforge-community/AM-HF-SYNC#g' -i "{}" + 2>/dev/null
          find "${GITHUB_WORKSPACE}/main/modules" -name ".git*" -prune -o -type f -exec sed 's#\^ivan-hc#\^Azathothas#g' -i "{}" + 2>/dev/null
          sed 's#\^ivan-hc#\^Azathothas#g' -i "${GITHUB_WORKSPACE}/main/APP-MANAGER"
          find "${GITHUB_WORKSPACE}/main/modules" -name ".git*" -prune -o -type f -exec sed 's#\TORSOCKS="1"#unset TORSOCKS#g' -i "{}" + 2>/dev/null
          sed 's#\TORSOCKS="1"#unset TORSOCKS#g' -i "${GITHUB_WORKSPACE}/main/APP-MANAGER"
          ##api.github.com --> api.gh.pkgforge.dev
          find "${GITHUB_WORKSPACE}/main" -name ".git*" -prune -o -type f -exec sed 's#api.github.com#api.gh.pkgforge.dev#g' -i "{}" + 2>/dev/null
          ##repology.org --> api.rl.pkgforge.dev
          find "${GITHUB_WORKSPACE}/main" -name ".git*" -prune -o -type f -exec sed 's#repology.org#api.rl.pkgforge.dev#g' -i "{}" + 2>/dev/null
          ###curl -$ARGS --> curl -A "${USER_AGENT}" -$ARGS
          #find "${GITHUB_WORKSPACE}/main" -name ".git*" -prune -o -type f -exec sed '/USER_AGENT/!s#curl -#curl -A "${USER_AGENT}" -#g' -i "{}" + 2>/dev/null
          ###wget "$ARGS --> wget -U "${USER_AGENT}" "$ARGS
          #find "${GITHUB_WORKSPACE}/main" -name ".git*" -prune -o -type f -exec sed '/USER_AGENT/!s#wget "#wget -U "${USER_AGENT}" "#g' -i "{}" + 2>/dev/null
          ##set -e --> set +e
          find "${GITHUB_WORKSPACE}/main" -name ".git*" -prune -o -type f -exec sed 's#set -e#set +e#g' -i "{}" + 2>/dev/null
          ###set -u --> set +u
          #find "${GITHUB_WORKSPACE}/main" -name ".git*" -prune -o -type f -exec sed 's#set -u#set +u#g' -i "{}" + 2>/dev/null
          ##set -u --> set -ux
          find "${GITHUB_WORKSPACE}/main/programs" -name ".git*" -prune -o -type f -exec sed '/set -ux/!s#set -u#set -ux#g' -i "{}" + 2>/dev/null
        continue-on-error: true
          
      - name: Update/Generate BUILD_LIST
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          ##AM
          pushd "$(mktemp -d)" &>/dev/null && git clone --filter="blob:none" --depth="1" --no-checkout "https://github.com/ivan-hc/AM" && cd "./AM"
          git sparse-checkout set "" && git checkout
          unset AM_REPO_LOCAL ; AM_REPO_LOCAL="$(realpath .)" && export AM_REPO_LOCAL="${AM_REPO_LOCAL}"
          if [ ! -d "${AM_REPO_LOCAL}" ] || [ $(du -s "${AM_REPO_LOCAL}" | cut -f1) -le 100 ]; then
            echo -e "\n[X] FATAL: Failed to clone AM Repo\n"
           exit 1
          fi
          popd &>/dev/null
          ##HF
          pushd "$(mktemp -d)" &>/dev/null && git clone --filter="blob:none" --depth="1" --no-checkout "https://huggingface.co/datasets/pkgforge/AMcache" && cd "./AMcache"
          git sparse-checkout set "" && git checkout
          unset HF_REPO_LOCAL ; HF_REPO_LOCAL="$(realpath .)" && export HF_REPO_LOCAL="${HF_REPO_LOCAL}"
          if [ ! -d "${HF_REPO_LOCAL}" ] || [ $(du -s "${HF_REPO_LOCAL}" | cut -f1) -le 100 ]; then
            echo -e "\n[X] FATAL: Failed to clone HF Repo\n"
           exit 1
          fi
          popd &>/dev/null
          ##Generate Input
          pushd "$(mktemp -d)" &>/dev/null
           curl -qfsSL "https://github.com/ivan-hc/AM/raw/main/programs/x86_64-appimages" | sort -u -o "./AI.txt"
           git -C "${AM_REPO_LOCAL}" ls-tree --name-only 'HEAD' -- "programs/x86_64/" | xargs -I "{}" basename "{}" | sort -u | sed -E 's/^[[:space:]]+|[[:space:]]+$//g' | grep -Eiv '\.(git|md|txt)' | sort -u -o "./APP.txt"
           readarray -t "AM_PKGS_X86_TMP" < <(grep -o -w -f "./APP.txt" "./AI.txt" | sed -E 's/^[[:space:]]+|[[:space:]]+$//g' | grep -Eiv '\.(git|md|txt)' | sort -u)
           if [[ -n "${AM_PKGS_X86_TMP[*]}" && "${#AM_PKGS_X86_TMP[@]}" -gt 2000 ]]; then
            #Update List
             printf "%s\n" "${AM_PKGS_X86_TMP[@]}" | sort -u -o "${GITHUB_WORKSPACE}/main/.github/PKG_LIST_x86_64-Linux.txt"
            #Remove Previous Builds
             readarray -t "QUEUE_LIST_X86" < <(sort -u "${GITHUB_WORKSPACE}/main/.github/QUEUE_LIST_x86_64-Linux.txt")
            #Reset Array to new
             AM_PKGS_X86=()
             readarray -t "AM_PKGS_X86" < <(printf "%s\n" "${AM_PKGS_X86_TMP[@]}" | sort -u | comm -23 - <(printf "%s\n" "${QUEUE_LIST_X86[@]}" | sort -u))
             echo -e "\n[+] AM_PKGS_X86 ==> ${#AM_PKGS_X86[@]}\n"
           fi
           #readarray -t "AM_PREBUILTS" < <(git -C "${HF_REPO_LOCAL}" ls-tree --name-only 'HEAD' | xargs -I "{}" basename "{}" | sort -u | sed -E 's/^[[:space:]]+|[[:space:]]+$//g' | grep -Eiv '\.(git|md|txt)')
           readarray -t "AM_PREBUILTS" < <(curl -qfsSL "https://meta.pkgforge.dev/external/am/x86_64-Linux.json" | jq -r '.[] | .pkg' | sort -u | sed -E 's/^[[:space:]]+|[[:space:]]+$//g')
           if [[ -n "${AM_PREBUILTS[*]}" && "${#AM_PREBUILTS[@]}" -gt 100 ]]; then
             printf "%s\n" "${AM_PREBUILTS[@]}" | sort -u -o "${GITHUB_WORKSPACE}/main/.github/CACHE_LIST.txt"
           fi
           ##Generate Build List
           #if [[ "${#AM_PKGS_X86[@]}" -gt 2000 && "${#AM_PREBUILTS[@]}" -gt 100 ]]; then
             comm -23 <(printf "%s\n" "${AM_PKGS_X86[@]}" | sort) <(printf "%s\n" "${AM_PREBUILTS[@]}" | sort) | sort -u -o "./BUILD_LIST.tmp"
             BUILD_LIST_TMP="$(wc -l < "./BUILD_LIST.tmp" | tr -cd '[:digit:]' | tr -d '[:space:]')"
             if [[ "${BUILD_LIST_TMP}" -gt 255 ]]; then
               echo -e "\n[+] Generating Build List (Diff from Prebuilts [${BUILD_LIST_TMP}])\n"
               sed -e '/^[[:space:]]*$/d;256q' "./BUILD_LIST.tmp" | sort -u -o "./BUILD_LIST_x86_64-Linux.txt"
             elif [[ "${BUILD_LIST_TMP}" -lt 10 ]]; then
               #echo -e "\n[+] Generating Build List (Diff from Prebuilts + PKG_LIST [${BUILD_LIST_TMP}])\n"
               #printf "%q\n" "${AM_PKGS_X86[@]:0:240}" | xargs -n1 | sort -u >> "./BUILD_LIST_x86_64-Linux.txt"
               sed -e '/^[[:space:]]*$/d;10q' "./BUILD_LIST.tmp" | sort -u -o "./BUILD_LIST_x86_64-Linux.txt"
               if [[ "$(wc -l < "./BUILD_LIST_x86_64-Linux.txt" | tr -cd '[:digit:]')" -lt 10 ]]; then
                  echo -e "\n[+] Generating Build List (Diff from Prebuilts + PKG_LIST + Old Prebuilts)\n"
                  curl -qfsSL "https://meta.pkgforge.dev/external/am/x86_64-Linux.json" | jq -r --arg CUT_OFF "$(date -u -d '5 days ago' +%Y-%m-%dT%H:%M:%SZ)" '[.[] | select(.build_date < $CUT_OFF) | .pkg][0:240] | .[]' | sort -u >> "./BUILD_LIST_x86_64-Linux.txt"
               fi
             else
               echo -e "\n[+] Generating Build List (Diff from BUILD_LIST [${BUILD_LIST_TMP}])\n"
               sed -e '/^[[:space:]]*$/d;256q' "./BUILD_LIST.tmp" | sort -u -o "./BUILD_LIST_x86_64-Linux.txt"
             fi
               cat "./BUILD_LIST_x86_64-Linux.txt" | sort -u | sed -E 's/^[[:space:]]+|[[:space:]]+$//g' | sed -e '/^[[:space:]]*$/d;256q' > "./file1.tmp"
               cat "${GITHUB_WORKSPACE}/main/.github/BUILD_LIST_x86_64-Linux.txt" | sort -u | sed -E 's/^[[:space:]]+|[[:space:]]+$//g' > "./file2.tmp"
               comm -3 "./file1.tmp" "./file2.tmp" | sort -u | sed -E 's/^[[:space:]]+|[[:space:]]+$//g' | sed -e '/^[[:space:]]*$/d;256q' > "${GITHUB_WORKSPACE}/main/.github/BUILD_LIST_x86_64-Linux.txt"
               sort -u "${GITHUB_WORKSPACE}/main/.github/BUILD_LIST_x86_64-Linux.txt" -o "${GITHUB_WORKSPACE}/main/.github/BUILD_LIST_x86_64-Linux.txt"
           #fi
           sed -E 's/^[[:space:]]+|[[:space:]]+$//g' -i "${GITHUB_WORKSPACE}/main/.github/CACHE_LIST.txt"
           sed -E 's/^[[:space:]]+|[[:space:]]+$//g' -i "${GITHUB_WORKSPACE}/main/.github/PKG_LIST_x86_64-Linux.txt"
           sed -E 's/^[[:space:]]+|[[:space:]]+$//g' -i "${GITHUB_WORKSPACE}/main/.github/BUILD_LIST_x86_64-Linux.txt"
           sed -E 's/^[[:space:]]+|[[:space:]]+$//g' -i "${GITHUB_WORKSPACE}/main/.github/QUEUE_LIST_x86_64-Linux.txt"
           echo -e "\n[+] Total Packages: $(wc -l < ${GITHUB_WORKSPACE}/main/.github/PKG_LIST_x86_64-Linux.txt)"
           echo -e "[+] Total Prebuilts: $(wc -l < ${GITHUB_WORKSPACE}/main/.github/CACHE_LIST.txt)"
           echo -e "[+] Total Build Queue: $(wc -l < ${GITHUB_WORKSPACE}/main/.github/BUILD_LIST_x86_64-Linux.txt)"
           echo -e "[+] Total Exclusions: $(wc -l < ${GITHUB_WORKSPACE}/main/.github/QUEUE_LIST_x86_64-Linux.txt)\n"
          popd &>/dev/null
        continue-on-error: true

      - name: Get DateTime
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          NEPALI_TIME="$(TZ='Asia/Kathmandu' date +'%Y-%m-%d (%I:%M:%S %p)')"
          echo "NEPALI_TIME=${NEPALI_TIME}" >> "${GITHUB_ENV}"
        continue-on-error: true
        
      - name: Pull & Push (1)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          cd "${GITHUB_WORKSPACE}/main"
          git pull origin main --no-edit 2>/dev/null
          git pull origin main --ff-only ; git merge --no-ff -m "Merge & Sync"
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main
          commit_user_name: Azathothas
          commit_user_email: AjamX101@gmail.com
          commit_message: "♻️ Synced AM 📦 <-- [${{ env.LATEST_COMMI_M }}] ⌚"
          
      - name: Pull & Push (2)
        run: |
          #Presets
          set +x ; set +e
          #--------------#
          cd "${GITHUB_WORKSPACE}/main"
          git pull origin main --no-edit 2>/dev/null
          git pull origin main --ff-only ; git merge --no-ff -m "Merge & Sync"
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main
          commit_user_name: Azathothas
          commit_user_email: AjamX101@gmail.com
          commit_message: "♻️ Synced AM 📦 <-- [${{ env.LATEST_COMMI_M }}] ⌚"
